extends: airbnb
parser: babel-eslint
rules:
  jsx-a11y/click-events-have-key-events: 0
  react/jsx-filename-extension: 0
  arrow-body-style: 0
  import/prefer-default-export: 0
  react/prop-types: 0
  jsx-a11y/anchor-is-valid: 0
  react/prefer-stateless-function: 0
  react/no-array-index-key: 0
  no-underscore-dangle: 0
  no-void: 0
  global-require: 0
  import/no-unresolved: 0
  import/extensions: 0
globals:
  document: 0
  window: 0
  localStorage: 0
  sessionStorage: 0
  fetch: 0
  FileReader: 0
  navigator: 0
