image: node:latest

cache:
  key: "$CI_JOB_NAME"
  untracked: true

stages:
  - build
  - deploy

build:
  stage: build
  only:
   - production
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - dist/

deploy:
  stage: deploy
  only:
   - production
  script:
    - node_modules/.bin/firebase deploy --non-interactive --token $FIREBASE_TOKEN
